app/controllers/daily_intakes_controller.rb
app/controllers/exercises_controller.rb
app/helpers/daily_intakes_helper.rb
app/helpers/exercises_helper.rb
app/javascript/controllers/hello_controller.js
app/javascript/controllers/index.js
app/javascript/controllers/turbo_modal_controller.js
app/views/daily_intakes/new.html.erb
app/views/daily_intakes/show.html.erb
app/views/dashboard/index.html.erb
app/views/exercises/new.html.erb
app/views/exercises/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb

this PR completes todo tasks 4-7 of issue #5 
https://user-images.githubusercontent.com/65844337/181408438-f4a968f5-e565-4da7-83ce-fc9946af5158.mp4

Design: Show and New page Turbo modals for Food Intakes and Exercieses Resources

---

Gemfile.lock
db/schema.rb
spec/factories/conversations.rb
spec/factories/members.rb
spec/factories/messages.rb
spec/factories/users.rb
spec/models/conversation_spec.rb
spec/models/member_spec.rb
spec/models/user_spec.rb

- Creates unit test for the present implementation of Conversation, Member, and User Models.
- Also creates respective factories for each model.
closes #17

UNIT TEST: Conversation, Member, and Message Model

---

app/controllers/application_controller.rb
app/controllers/users/registrations_controller.rb
app/views/layouts/devise.html.erb
app/views/users/registrations/new.html.erb
app/views/users/sessions/new.html.erb
app/views/users/shared/_links.html.erb
config/routes.rb

This PR completes todo items 10-11 of issue #5

Design: Devise pages

---

app/controllers/notifications_controller.rb
app/helpers/notifications_helper.rb
app/javascript/icons/bell.svg
app/views/dashboard/index.html.erb
app/views/layouts/application.html.erb
app/views/notifications/index.html.erb
app/views/posts/index.html.erb
config/routes.rb
spec/helpers/notifications_helper_spec.rb
spec/requests/notifications_spec.rb
spec/views/notifications/index.html.erb_spec.rb

This PR completes item no.3 notifications Design of issue #5 
I also added working links on the side navigations
Also fixed the vh height scrolling

Design: Notification Static UI

---

app/controllers/conversation_messages_controller.rb
app/models/message.rb
app/views/conversation_messages/_message.html.erb
app/views/direct_conversations/show.html.erb
app/views/layouts/application.html.erb
db/migrate/20220727125536_create_messages.rb
db/schema.rb

closes #38 
- Fixed layout already
- Needed to do unconventional workarounds (especially putting data attribute in head element) to make it work hahahhahahaha!
- Yung sa seen, hindi ko pa muna priority, will revisit it after we're done with MVP.

FIX: Bubble Message Layout in Conversation when Appending Partial via Turbo Stream

---

app/controllers/follows_controller.rb
app/helpers/follows_helper.rb
app/models/relationship.rb
app/models/user.rb
app/views/posts/index.html.erb
config/routes.rb
db/migrate/20220804012857_drop_follows_table.rb
db/migrate/20220804020538_create_relationships.rb
db/schema.rb
spec/factories/relationships.rb
spec/helpers/follows_helper_spec.rb
spec/models/relationship_spec.rb
spec/requests/follows_spec.rb

Hi guys pareview, same approach as likes yung ginawa ko dito, same din na yung uniqueness is on database level yung validation. Thanks!

FEATURE: follow and unfollow users

---

app/controllers/comments_controller.rb
app/controllers/likes_controller.rb
app/controllers/posts_controller.rb
app/models/comment.rb
app/models/conversation.rb
app/models/like.rb
app/models/post.rb
app/views/direct_conversations/_my_message.html.erb
app/views/direct_conversations/_other_message.html.erb
app/views/posts/_comment.html.erb
app/views/posts/_like.html.erb
app/views/posts/index.html.erb
app/views/posts/show.html.erb

FEATURE: Realtime Update of Like Count and Comments

---

app/controllers/likes_controller.rb
app/models/like.rb
app/models/notification.rb
app/models/user.rb
app/notifications/like_notification.rb
db/migrate/20220804012857_drop_follows_table.rb
db/schema.rb

FEATURE: Addition of Like Notifications

---

.gitignore
Procfile.dev
db/schema.rb

Chore: add redis to procfile

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/notifications/comment_notification.rb
app/notifications/conversation_notification.rb
app/notifications/like_notification.rb
app/notifications/message_notification.rb
app/views/layouts/application.html.erb
app/views/notifications/_read_notification.html.erb
app/views/notifications/_unread_notification.html.erb
app/views/users/registrations/edit.html.erb

DESIGN: Add Helper Method for Rendering Avatar in Views

---

app/controllers/profile_controller.rb
app/controllers/users/registrations_controller.rb
app/helpers/profile_helper.rb
app/views/profile/edit.html.erb
app/views/profile/show.html.erb
app/views/users/registrations/edit.html.erb
config/routes.rb
spec/helpers/profile_helper_spec.rb
spec/requests/profile_spec.rb

FEATURE: Edit User Profile

---

app/controllers/foods_controller.rb
app/helpers/foods_helper.rb
app/models/food.rb
app/models/user.rb
app/views/foods/edit.html.erb
app/views/foods/index.html.erb
app/views/foods/new.html.erb
app/views/foods/show.html.erb
config/routes.rb
db/migrate/20220805114828_create_foods.rb
db/schema.rb
spec/factories/foods.rb
spec/helpers/foods_helper_spec.rb
spec/models/food_spec.rb
spec/requests/foods_spec.rb

FEATURE: CRUD Food Resource

---

app/controllers/foods_controller.rb
app/controllers/foods_meals_controller.rb
app/controllers/meals_controller.rb
app/helpers/meals_helper.rb
app/models/food.rb
app/models/meal.rb
app/models/user.rb
app/views/foods/edit.html.erb
app/views/foods_meals/new.html.erb
app/views/meals/edit.html.erb
app/views/meals/index.html.erb
app/views/meals/new.html.erb
app/views/meals/show.html.erb
config/routes.rb
db/migrate/20220805223004_create_meals.rb
db/migrate/20220805231727_create_foods_meals.rb
db/schema.rb
spec/factories/meals.rb
spec/helpers/meals_helper_spec.rb
spec/models/meal_spec.rb
spec/requests/meals_spec.rb

FEATURE: Creation of Meals and Addition of Food in a Meal

---

app/controllers/direct_conversations_controller.rb
app/helpers/direct_conversations_helper.rb
app/models/conversation.rb
app/models/member.rb
app/views/direct_conversations/_conversation.html.erb
app/views/direct_conversations/index.html.erb
app/views/direct_conversations/show.html.erb
db/schema.rb

- also brought back the realtime unread messages count

FIX: Send Message Bug

---

app/controllers/dashboard_controller.rb
app/controllers/foods_controller.rb
app/controllers/repetition_exercises_controller.rb
app/controllers/timed_exercises_controller.rb
app/javascript/controllers/calendar_controller.js
app/javascript/controllers/index.js
app/views/daily_intakes/index.html.erb
app/views/dashboard/index.html.erb
app/views/foods/_table.html.erb
app/views/foods/index.html.erb
app/views/repetition_exercises/_table.html.erb
app/views/repetition_exercises/index.html.erb
app/views/repetition_exercises/new.html.erb
app/views/timed_exercises/_table.html.erb
app/views/timed_exercises/index.html.erb
app/views/timed_exercises/new.html.erb
db/schema.rb
package.json
yarn.lock

this resolves #64
https://user-images.githubusercontent.com/65844337/183537793-12c3c828-2267-4bd0-b54f-e6899e78ff1b.mp4

DESIGN: Dashboard UI

---

app/models/daily_intake_food.rb
spec/factories/daily_intake_foods.rb
spec/factories/daily_intakes.rb
spec/factories/foods.rb
spec/factories/meals.rb
spec/factories/posts.rb
spec/models/daily_intake_food_spec.rb
spec/models/daily_intake_spec.rb
spec/models/food_spec.rb
spec/models/like_spec.rb
spec/models/meal_spec.rb
spec/models/member_spec.rb
spec/models/notification_spec.rb
spec/models/post_spec.rb
spec/models/relationship_spec.rb
spec/models/repetition_exercise_spec.rb
spec/models/report_spec.rb
spec/models/timed_exercise_spec.rb
spec/models/user_spec.rb

closes #79 #85 #86 #87 #88 #89 #91 #92 #93 #94 #95
pasensya na natuwa masyado na pwedeng gawing issue yung isang task hahahahahahaha

TEST: Model Tests

---

Gemfile
Gemfile.lock
db/schema.rb
spec/system/send_message_spec.rb

- very basic system test that may serve as a reference (made it very simple para pwedeng reference)

TEST: Sending of Message

---

spec/system/like_post_spec.rb

TEST: Like a post

---

app/controllers/daily_intake_meals_controller.rb
app/controllers/daily_intakes_controller.rb
app/controllers/meals_controller.rb
app/controllers/routine_exercises_controller.rb
app/views/daily_intake_foods/new.html.erb
app/views/daily_intake_meals/new.html.erb
app/views/daily_intakes/_daily_intakes.html.erb
app/views/dashboard/index.html.erb
app/views/foods/_table.html.erb
app/views/foods/new.html.erb
app/views/meals/_table.html.erb
app/views/meals/edit.html.erb
app/views/meals/new.html.erb
app/views/repetition_exercises/_table.html.erb
app/views/repetition_exercises/new.html.erb

This completes second part of #96

Design/intake form UI

---

spec/system/create_post_spec.rb

Hi guys pareview ulit, thanks!

TEST: Create a post

---

app/controllers/exercise_schedules_controller.rb
app/controllers/google_oauth_calendar_controller.rb
app/javascript/controllers/calendar_controller.js
app/javascript/controllers/index.js
app/views/dashboard/index.html.erb
app/views/exercise_schedules/_dashboard.html.erb
app/views/exercise_schedules/_preview.html.erb
app/views/exercise_schedules/new.html.erb
config/routes.rb
package.json
yarn.lock

Design: schedule form

---

app/controllers/application_controller.rb

FIX: Signup Not Working

---

app/javascript/controllers/calendar_controller.js
app/services/google_calendar/events_fetcher.rb
db/migrate/20220811171226_add_description_to_routine.rb
db/schema.rb

FEATURE: Gcal Schedule Calendar

---

app/controllers/foods_controller.rb
app/controllers/meals_controller.rb
app/controllers/repetition_exercises_controller.rb
app/controllers/timed_exercises_controller.rb
app/javascript/controllers/tom_select_controller.js
app/views/daily_intake_foods/new.html.erb
app/views/daily_intake_meals/new.html.erb
app/views/dashboard/index.html.erb
app/views/foods/_item.html.erb
app/views/foods/_table.html.erb
app/views/foods/create.turbo_stream.erb
app/views/layouts/application.html.erb
app/views/meals/_item.html.erb
app/views/meals/_table.html.erb
app/views/meals/create.turbo_stream.erb
app/views/meals/new.html.erb
app/views/repetition_exercises/_item.html.erb
app/views/repetition_exercises/_table.html.erb
app/views/repetition_exercises/create.turbo_stream.erb
app/views/routines/_form.html.erb
app/views/routines/_option.html.erb
app/views/routines/new.html.erb
app/views/shared/_flash.html.erb
app/views/timed_exercises/_item.html.erb
app/views/timed_exercises/_table.html.erb
app/views/timed_exercises/create.turbo_stream.erb
package.json
yarn.lock

superspike7@02033c0 closes #136, and the rest closes #137

POLISH: Turbo Stream on Creation and Update + Daily Intake Modal

---

app/assets/images/icons/solid_heart.svg
app/controllers/application_controller.rb
app/controllers/daily_intakes_controller.rb
app/controllers/dashboard_controller.rb
app/controllers/exercise_schedules_controller.rb
app/controllers/foods_controller.rb
app/controllers/likes_controller.rb
app/controllers/routines_controller.rb
app/views/admin/reports/index.html.erb
app/views/admin/users/index.html.erb
app/views/exercise_schedules/_preview.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
app/views/notifications/_read_notification.html.erb
app/views/notifications/_unread_notification.html.erb
app/views/posts/_post.html.erb
app/views/routines/_form.html.erb
db/migrate/20220811171226_add_description_to_routine.rb
db/schema.rb

POLISH: Like SVG and Fix for Notification Image
